In [0]:
import torch

In [0]:
def activation(x):
  """ sigmoid activation function

      Arguments
      ---------
      
      x: torch.tensor
  """
  return 1 / ( 1 + torch.exp(-x))

In [0]:
torch.manual_seed(8)

features = torch.randn([1,5]) 

weights = torch.rand_like(features)

bias = torch.ones([1,1])

In [0]:
weights = torch.reshape( weights , [5,1])

In [0]:
# matmul using torch.sum
output = activation(torch.sum(features * weights) + bias)

In [0]:
# matmul using torch.mm and torch.matmul
ouput1 = torch.mm(features , weights) + bias)

In [0]:
activation.__doc__

' sigmoid activation function\n\n      Arguments\n      ---------\n\n      x: torch.tensor\n  '

In [0]:
# building our first neural network
n_input = 3
n_hidden = 2
output = 1

torch.manual_seed(1)

features = torch.randn([1,3])

W1 = torch.randn([n_input , n_hidden])
W2 = torch.randn([n_hidden , output])

B1 = torch.randn([1,n_hidden])
B2 = torch.randn([1,output])

In [0]:
hidden = activation(torch.mm(features , W1) + B1)
y = activation(torch.mm(hidden , W2) + B2)

In [0]:
y

tensor([[0.1766]])

**NUMPY TO TORCH AND BACK**

In [0]:
import numpy as np
array = np.random.randn(2,3)
array

array([[ 1.13900235,  0.81429053,  0.5293066 ],
       [ 0.90081776, -1.40208984,  0.87078187]])

In [0]:
b =torch.from_numpy(array)
b

tensor([[ 1.1390,  0.8143,  0.5293],
        [ 0.9008, -1.4021,  0.8708]], dtype=torch.float64)

In [0]:
# back to numpy
b.numpy()

array([[ 1.13900235,  0.81429053,  0.5293066 ],
       [ 0.90081776, -1.40208984,  0.87078187]])