In [0]:
import torch

In [0]:
print(torch.__version__)

1.4.0


In [0]:
torch.cuda.is_available()

True

In [0]:
torch.version.cuda

'10.1'

**Attributes of Tensor**

In [0]:
# 1 . rank --> tells the dimension of the tensor

d = [
[ 1,2,3],
[3,4,5],
[6,7,8]
]

In [0]:
dd = torch.tensor(d)

In [0]:
dd

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
dd.shape

torch.Size([3, 3])

In [0]:
# axis --> how many indices is required to acces the element...of if 2d tesnor then 2 axis are required and last axis all retrun only one number while the others return the nd array


In [0]:
#shape
dd.shape

torch.Size([3, 3])

In [0]:
#reshape
dd.reshape(1,9)

tensor([[1, 2, 3, 3, 4, 5, 6, 7, 8]])

Creation option using data

In [0]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [0]:
torch.Tensor(a)

tensor([1., 2., 3.])

In [0]:
torch.tensor(a)

tensor([1, 2, 3])

In [0]:
torch.as_tensor(a)

tensor([1, 2, 3])

In [0]:
torch.from_numpy(a)

tensor([1, 2, 3])

In [0]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [0]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
torch.rand(2,3)

tensor([[0.8623, 0.6091, 0.6034],
        [0.9703, 0.4155, 0.4782]])

**Creating pytorch tesnors - Best options**

In [0]:
data  = np.array([1,2,3,4])

In [0]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [0]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [0]:
torch.get_default_dtype()

torch.float32

In [0]:
data = np.array([4,4,4,4])

In [0]:
data[0]=1
data[1]=1

In [0]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([0., 0., 4., 4.])
tensor([0, 0, 4, 4])
tensor([1, 1, 4, 4])
tensor([1, 1, 4, 4])


**Tesnor operation types**


*   Reshape
*   Flatten

*   Element-wise operation
*   Access operation







In [0]:
t = torch.tensor([
              [1,1,1,1],
              [2,2,2,2],
              [3,3,3,3],
              ] , dtype = torch.float32)

In [0]:
print(t)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


In [0]:
# to get the size of the tesnor
t.size()

torch.Size([3, 4])

In [0]:
t.shape

torch.Size([3, 4])

In [0]:
# reshaping the tensor
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [0]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])